[project]
name = 'maxprov'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.anonymization]
path = 'contracts/anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.community_governance]
path = 'contracts/community_governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.container_with_multi_user_inputs]
path = 'contracts/container_with_multi_user_inputs.clar'
clarity_version = 2
epoch = 2.5

[contracts.decentralized_identity]
path = 'contracts/decentralized_identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.event_logging]
path = 'contracts/event_logging.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_deletion]
path = 'contracts/file_deletion.clar'
clarity_version = 2
epoch = 2.5

[contracts.gooo]
path = 'contracts/gooo.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact_report]
path = 'contracts/impact_report.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_signature_wallet]
path = 'contracts/multi_signature_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.tokenized_data]
path = 'contracts/tokenized_data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
